mode: train
smpl_pos_map: smpl_pos_map_smplx
train:
  dataset: MvRgbDatasetActorsHQ
  data:
    # layers: ["body", "cloth"]
    subject_name: actor08
    data_dir: /data/zhiychen/ActorHQ/Actor08/Sequence1/4x
    frame_range: 
    - 0
    - 2000
    - 2
    used_cam_ids: [7, 22, 39, 56, 79, 80, 95,
                    109, 112, 126, 127,
                    151, 152, 160]
    load_smpl_pos_map: true
    use_label: true
    use_body_label: false
    use_normal: true
  pretrained_dir: null
  net_ckpt_dir: /data/zhiychen/AnimatableGaussain/results/ActorHQ/actor08_layga_retrain
  inner_ckpt_dir: null
  prev_ckpt: /data/zhiychen/AnimatableGaussain/results/ActorHQ/actor08_layga/epoch_latest
  ckpt_interval:
    epoch: 5
    batch: 5000
  eval_interval: 1000
  dropout_interval: 10000000
  eval_training_ids: [750, 127]
  eval_testing_ids: [1460, 127]
  eval_img_factor: 1.0
  lr_init: 0.00015
  loss_weight:
    l1: 0.5
    lpips: 0.1
    face_lpips: 0.
    ssim: 0.0
    offset: 0.005
    laplacian: 0.
    body_loss: 0
    consistent_body_color: 0.
    consistent_label: 0.1
    consistent_label_body: 0.
    opacity_loss: 0.
    normal_loss: 0.025
    inner_cloth_laplacian: 0.00
    inner_cloth_loss: 0
    outer_to_body_loss: 0.
  finetune_color: false
  batch_size: 1
  num_workers: 8
  random_bg_color: true
  gd_clip: 0.001
test:
  dataset: MvRgbDatasetActorsHQ
  # render_layers: ["cloth"]
  data:
    subject_name: actor08_novel_view
    data_dir: /data/zhiychen/ActorHQ/Actor08/Sequence1/4x
    frame_range: 
    - 0
    - 2000
    - 2
    used_cam_ids: [7, 22, 39, 56, 79, 80, 95,
                    109, 112, 126, 127,
                    151, 152, 160]
  view_setting: camera
  render_view_idx: 128
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  fix_hand: false
  fix_hand_id: 431
  n_pca: -1
  sigma_pca: 2.0
  prev_ckpt: /data/zhiychen/AnimatableGaussain/results/ActorHQ/actor08_layga_retrain/epoch_latest
model:
  with_viewdirs: true
  random_style: false
  offset_mode: original
  module: network.layga
  network: LayGaNet
exchange_cloth:
  dataset: MvRgbDataset4DDress
  render_layers: ["both"]
  data_dir: /data/zhiychen/AnimatableGaussain/test_data/multiviewRGC/4d_dress/cloth_00185_body_00134_test/Outer
  data_cloth:
    layers: ["body", "cloth", "outer"]
    subject_name: 185134_outer
    data_dir: /data/zhiychen/AnimatableGaussain/test_data/multiviewRGC/4d_dress/cloth_00185_body_00134_test/Outer/cloth
  data_body:
    layers: ["body", "cloth"]
    subject_name: 185134_outer
    data_dir: /data/zhiychen/AnimatableGaussain/test_data/multiviewRGC/4d_dress/cloth_00185_body_00134_test/Outer/body
  view_setting: camera
  render_view_idx: 1
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  fix_hand: false
  fix_hand_id: 431
  n_pca: -1
  sigma_pca: 2.0
  body_ckpt:  /data/zhiychen/AnimatableGaussain/results/4d_dress/00134/neutral_new_pose_param/epoch_latest
  cloth_ckpt:  /data/zhiychen/AnimatableGaussain/results/4d_dress/00185/outer_inner/epoch_latest
