mode: train
smpl_pos_map: smpl_pos_map_offset
sequence_name: smpl_params
train:
  dataset: MvRgbDataset4DDress
  data:
    layers: ["body", "cloth"]
    subject_name: 185
    data_dir: /data/zhiychen/AnimatableGaussain/train_data/multiviewRGC/4d_dress/00185/Inner
    used_cam_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    # frame_range:
    # - 0
    # - 1
    # - 1
    load_smpl_pos_map: true
    use_label: true
    use_body_label: true
    use_normal: false
  pretrained_dir: null
  net_ckpt_dir: /mnt/work/Clothes4D/zhiychen/results/4d_dress/00185/virtual_bone_body_loss
  inner_ckpt_dir: null
  prev_ckpt: null
  ckpt_interval:
    epoch: 3
    batch: 1000
  eval_interval: 1000
  dropout_interval: 10000
  eval_training_ids: [20, 1]
  eval_testing_ids: [90, 1]
  eval_img_factor: 1.0
  lr_init: 0.00015
  loss_weight:
    l1: 1
    lpips: 0.1
    face_lpips: 0.
    ssim: 0.05
    offset: 0.005
    laplacian: 0.0
    body_loss: 0.5
    consistent_body_color: 0.00
    consistent_label: 0.75
    consistent_label_body: 0.01
    opacity_loss: 0.001
    normal_loss: 0.
    inner_cloth_laplacian: 0.00
    inner_cloth_loss: 0
    outer_to_body_loss: 0
  finetune_color: false
  batch_size: 1
  num_workers: 8
  random_bg_color: true
  gd_clip: 0.0001
test:
  dataset: MvRgbDataset4DDress
  render_layers: ["both"]
  data:
    layers: ["body", "cloth"]
    subject_name: 00185_virtual_bones
    data_dir: /data/zhiychen/AnimatableGaussain/test_data/multiviewRGC/4d_dress/00185/Inner
    # frame_range:
    # - 150
    # - 310
    # - 1
  view_setting: camera
  render_view_idx: 1
  global_orient: true
  img_scale: 1
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  fix_hand: false
  fix_hand_id: 0
  n_pca: -1
  sigma_pca: 2.0
  prev_ckpt: /mnt/work/Clothes4D/zhiychen/results/4d_dress/00185/virtual_bone_body_loss/epoch_latest
model:
  with_viewdirs: t
  random_style: false
  cover: true
  offset_mode: original
  module: network.multi_layer_avatar
  network: MultiLAvatarNet
  virtual_bone: true
  deformation_graph_network:
    d_in: 3
    d_out: 6
    depth: 4
    width: 256
    multires: 0
    skip_layer: []
    cond_layer: [0]
    dim_cond_embed: 0
    weight_norm: True
exchange_cloth:
  dataset: MvRgbDataset4DDress
  render_layers: ["cloth"]
  seq_name: "squats"
  change_mode: cross_change_inner
  data_dir: /data/zhiychen/AnimatableGaussain/train_data/multiviewRGC/4d_dress/00127/Inner
  data_lower:
    frame_range:
    - 310
    - 455
    - 1
    layers: ["body", "cloth"]
    subject_name: 127_train
    data_dir: /data/zhiychen/AnimatableGaussain/train_data/multiviewRGC/4d_dress/00127/Inner
  data_upper:
    frame_range:
    - 310
    - 455
    - 1
    layers: ["body", "cloth"]
    subject_name: 127_train
    data_dir: /data/zhiychen/AnimatableGaussain/train_data/multiviewRGC/4d_dress/00127/Inner
  data_body:
    frame_range:
    - 310
    - 455
    - 1
    layers: ["body", "cloth"]
    subject_name: 127_train
    data_dir: /data/zhiychen/AnimatableGaussain/train_data/multiviewRGC/4d_dress/00127/Inner
  view_setting: camera
  render_view_idx: 0
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  fix_hand: false
  fix_hand_id: 431
  n_pca: -1
  sigma_pca: 2.0
  body_ckpt:  /data/zhiychen/AnimatableGaussain/results/4d_dress/00127/body_loss/epoch_latest
  upper_ckpt:  /data/zhiychen/AnimatableGaussain/results/4d_dress/00127/body_loss/epoch_latest
  lower_ckpt:  /data/zhiychen/AnimatableGaussain/results/4d_dress/00127/body_loss/epoch_latest
